### ISSUE TITLE
TuneIn

### ISSUE THREAD

**Issue by bighand01691** [joaconigro/plugin.audio.tuneinradio#6]
Hi. Will this addon ever be fixed. Not worked since its release.
Thanks

**Comment by joaconigro** [comment]
Hi @bighand01691, could you elaborate a little bit more, please?

What specifically isn't working?
What OS are you using?
Which version of this plugin did you try?
Provide some logs

I've been using this plugin since I released the first version for Leia and it's working fine. And I tested on Windows, Linux (elementary OS) y LibreElec (on RPi2)

**Comment by bighand01691** [comment]
Sorry i guess some info may help.

Matrix version 4.0 on Kodi 19.1

Cant login or use any function of plugin.

I hope log attached is correct. First time ive tried doing this.

Thanks

[kodi.log](https://github.com/joaconigro/plugin.audio.tuneinradio/files/6796942/kodi.log)

**Comment by joaconigro** [comment]
I see you are using an Android device. I don't have one to test, but this bug seems related to #3.

Try this. Go to the plugin settings -> advance -> and enable the option "Use UTF-8 encoding". Save the changes and restart the device.

Please, let me know if that works for you.

**Comment by bighand01691** [comment]
Tried it. Still not working. 😒

**Comment by joaconigro** [comment]
Ok, could you send the log when you use the plugin with the Use UTF-8 encoding enabled?

**Comment by bighand01691** [comment]
[kodi.log](https://github.com/joaconigro/plugin.audio.tuneinradio/files/6797124/kodi.log)

**Comment by joaconigro** [comment]
Well, I uploaded a new version (4.0.1) which updates some deprecated path related functions. You can download from here: https://github.com/joaconigro/plugin.audio.tuneinradio/releases/tag/4.0.1

Before installing the new version, remove the current version and **remove all the saved settings too**. Install the new version and remember to enable the UFT-8 encoding.

Please, let me know if that works for you.

**Comment by bighand01691** [comment]
Sir, you are a legend. Works a treat now. Great to see a dev who cares and helps. Thank you so much.

**Comment by joaconigro** [comment]
You're welcome. Maybe I don't have all the time I want to spend on my personal projects, but today you found me with enough time. ;)

And thank you for reporting the errors.

I'll close this issue.
